name: check-package-version
on:
  pull_request:
    branches:
      - master
jobs:
  check-package-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Get NPM version is new
        id: check
        uses: EndBug/version-check@v2.1.1
        with:
          diff-search: true
          file-name: ./package.json
          file-url: https://unpkg.com/eslint-plugin-boundaries@latest/package.json
          static-checking: localIsNew
      - name: Check version is new
        if: steps.check.outputs.changed != 'true'
        run: |
          echo "Version not changed"
          exit 1
      - name: Get NPM version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@v1.2.3
      - name: Check Changelog version
        id: changelog_reader
        uses: mindsers/changelog-reader-action@v2.2.2
        with:
          version: ${{ steps.package-version.outputs.current-version }}
          path: ./CHANGELOG.md
      - name: Read version from Sonar config
        id: sonar-version
        uses: christian-draeger/read-properties@1.1.1
        with:
          path: './sonar-project.properties'
          properties: 'sonar.projectVersion'
      - name: Check Sonar version
        if: steps.sonar-version.outputs.value != steps.package-version.outputs.current-version
        run: |
          echo "Version not changed"
          exit 1
